### ISSUE TITLE
More power

### ISSUE THREAD

**Issue by ghost** [Chatur27/Eureka-kernel-for-SM-A105-Pie#1]
This isnt really an issue but why arent the big ones overclocked to 2.3? Would be nice if youd add that :)

**Comment by Chatur27** [comment]
> This isnt really an issue but why arent the big ones overclocked to 2.3? Would be nice if youd add that :)

Hi, I myself have an A10 and I tried to overclock big cluster to 2184 MHz.
Unfortunately, phone would randomly reboot.
This is because the device is not supplying enough voltage to the chip.
So 2080 is the maximum stable frequency for this phone.
One solution is to change voltage supplied but since I didn't make the chip, I don't want to mess with that and fry my phone :)

Supplying more voltage means higher temperature, increasing risk of damaging chip
